CREATE TABLE  "EVENT_TABLE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"GAME_ID" NUMBER, 
	"INSTANCE_ID" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(3) COLLATE "USING_NLS_COMP", 
	"LEVEL" NUMBER, 
	"SCORE" NUMBER, 
	"X" NUMBER, 
	"Y" NUMBER, 
	"Z" NUMBER, 
	"STATE" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" TIMESTAMP (6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "EVENT_TABLE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/

BEGIN
  ORDS.enable_object (
    p_enabled      => TRUE, -- Default  { TRUE | FALSE }
    p_schema       => 'OCIARCADE',
    p_object       => 'EVENT_TABLE',
    p_object_type  => 'TABLE', -- Default  { TABLE | VIEW }
    p_object_alias => 'event_table',
    p_auto_rest_auth => TRUE
  );
  COMMIT;
END;
/

DECLARE
  l_priv_roles owa.vc_arr;
  l_priv_patterns owa.vc_arr;
BEGIN
  l_priv_roles(1) := 'oracle.dbtools.role.autorest.OCIARCADE.EVENT_TABLE';
  l_priv_roles(2) := 'ociarcade api';
  l_priv_roles(3) := 'oracle.dbtools.autorest.any.schema';
  l_priv_roles(4) := 'SQL Developer';
  l_priv_patterns(1) := '/metadata-catalog/event_table/*';
  l_priv_patterns(2) := '/event_table/*';

  ords.define_privilege(
    p_privilege_name     => 'oracle.dbtools.autorest.privilege.OCIARCADE.EVENT_TABLE',
    p_roles              => l_priv_roles,
    p_patterns           => l_priv_patterns,
    p_label              => 'oracle.dbtools.autorest.privilege.OCIARCADE.EVENT_TABLE',
    p_description        => 'oracle.dbtools.autorest.privilege.OCIARCADE.EVENT_TABLE'
  );
  COMMIT;
END;
/
